=== AubinMahe/dab/distributed-application-generation.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema
   xmlns:xs="http://www.w3.org/2001/XMLSchema"
   attributeFormDefault="unqualified"
   elementFormDefault="qualified">

   <xs:include schemaLocation="distributed-application-common.xsd" />

   <xs:complexType name="typeImplType">
      <xs:attribute type="languageType" name="language"    use="required" />
      <xs:attribute type="xs:string"    name="src-dir"     use="required" />
      <xs:attribute type="xs:string"    name="module-name" use="required" />
   </xs:complexType>

   <xs:complexType name="typesType">
      <xs:sequence>
         <xs:element type="typeImplType"   name="type-impl" minOccurs="1" maxOccurs="unbounded" />
      </xs:sequence>
      <xs:attribute type="xs:ID" name="name" />
   </xs:complexType>

   <xs:complexType name="compImplType">
      <xs:attribute type="xs:ID"        name="name"        use="required" />
      <xs:attribute type="languageType" name="language"    use="required" />
      <xs:attribute type="xs:string"    name="src-dir"     use="required" />
      <xs:attribute type="xs:string"    name="module-name" use="required" />
   </xs:complexType>

   <xs:complexType name="componentType">
      <xs:sequence>
         <xs:element type="compImplType" name="comp-impl" minOccurs="1" maxOccurs="unbounded" />
      </xs:sequence>
      <xs:attribute type="xs:ID" name="name" use="required" />
   </xs:complexType>
   
   <xs:simpleType name="portNumberType">
      <xs:restriction base="xs:int">
         <xs:minInclusive value="1" />
         <xs:maxInclusive value="65535" />
      </xs:restriction>
   </xs:simpleType>
   
   <xs:complexType name="compImplRefType">
      <xs:attribute type="xs:IDREF"     name="name"        use="required" />
   </xs:complexType>

   <xs:complexType name="factoryType">
      <xs:sequence>
         <xs:element type="compImplRefType" name="comp-impl-ref" minOccurs="0" maxOccurs="unbounded" />
      </xs:sequence>
      <xs:attribute type="languageType" name="language"    use="required" />
      <xs:attribute type="xs:string"    name="src-dir"     use="required" />
      <xs:attribute type="xs:string"    name="module-name" use="required" />
   </xs:complexType>

   <xs:complexType name="processType">
      <xs:sequence>
         <xs:element type="factoryType" name="factory" minOccurs="1" maxOccurs="unbounded" />
      </xs:sequence>
      <xs:attribute type="processName"    name="name"    use="required" />
      <xs:attribute type="xs:string"      name="address" use="required" />
      <xs:attribute type="portNumberType" name="port"    use="required" />
   </xs:complexType>

   <xs:simpleType name="dottedPath">
      <xs:restriction base="xs:string">
         <xs:pattern value="[^.]+\.[^.]+" />
      </xs:restriction>
   </xs:simpleType>

   <xs:complexType name="processRefType">
      <xs:attribute type="deploymentName" name="deployment" use="required" />
      <xs:attribute type="processName"    name="process" use="required" />
   </xs:complexType>

   <xs:complexType name="deploymentType">
      <xs:sequence>
	      <xs:choice minOccurs="0" maxOccurs="unbounded">
	         <xs:element type="processType"    name="process" />
	         <xs:element type="processRefType" name="process-ref" />
	      </xs:choice>
      </xs:sequence>
      <xs:attribute type="deploymentName" name="name" use="required" />
   </xs:complexType>

   <xs:complexType name="typesImplType">
      <xs:attribute type="languageType" name="language"    use="required" />
      <xs:attribute type="xs:string"    name="module-name" use="required" />
      <xs:attribute type="xs:string"    name="src-dir"     use="required" />
   </xs:complexType>

   <xs:complexType name="disappGenType">
      <xs:sequence>
         <xs:element type="typesType"      name="types"      minOccurs="0" maxOccurs="unbounded" />
         <xs:element type="componentType"  name="component"  minOccurs="1" maxOccurs="unbounded" />
         <xs:element type="deploymentType" name="deployment" minOccurs="1" maxOccurs="unbounded" />
      </xs:sequence>
   </xs:complexType>

   <xs:element name="distributed-application-generation" type="disappGenType" />

</xs:schema>

=== AubinMahe/dab/dab-gen.xml
<?xml version="1.0" encoding="UTF-8"?>
<distributed-application-generation xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
   xsi:noNamespaceSchemaLocation="distributed-application-generation.xsd"
   xmlns:xi="http://www.w3.org/2001/XInclude">

   <types name="dabtypes">
      <type-impl language="C"    src-dir="dabtypes-c/src-gen"    module-name="DBT" />
      <type-impl language="C++"  src-dir="dabtypes-cpp/src-gen"  module-name="hpms::dabtypes" />
      <type-impl language="Java" src-dir="dabtypes-java/src-gen" module-name="hpms.dabtypes" />
   </types>

   <component name="Distributeur">
      <comp-impl name="distributeur-c"        language="C"    src-dir="Distributeur-c/src-gen"             module-name="DAB" />
      <comp-impl name="distributeur-cpp"      language="C++"  src-dir="Distributeur-cpp/src-gen"           module-name="hpms::dab" />
      <comp-impl name="distributeur-java"     language="Java" src-dir="Distributeur-java/src-gen"          module-name="hpms.dab" />
      <comp-impl name="distributeur-scripted" language="Java" src-dir="Distributeur-scripted-java/src-gen" module-name="hpms.scripted.dab" />
   </component>

   <component name="Controleur">
      <comp-impl name="controleur-c"    language="C"    src-dir="Controleur-c/src-gen"    module-name="UDT" />
      <comp-impl name="controleur-cpp"  language="C++"  src-dir="Controleur-cpp/src-gen"  module-name="hpms::udt" />
      <comp-impl name="controleur-java" language="Java" src-dir="Controleur-java/src-gen" module-name="hpms.udt" />
   </component> 

   <component name="Banque">
      <comp-impl name="banque-c"    language="C"    src-dir="Banque-c/src-gen"    module-name="SC" />
      <comp-impl name="banque-cpp"  language="C++"  src-dir="Banque-cpp/src-gen"  module-name="hpms::sc" />
      <comp-impl name="banque-java" language="Java" src-dir="Banque-java/src-gen" module-name="hpms.sc" />
   </component>

   <deployment name="isolated">
      <process name="sc" address="127.0.0.1" port="2416">
         <factory language="C"    src-dir="isolated-sc-c/src-gen"    module-name="ISOSC" />
         <factory language="C++"  src-dir="isolated-sc-cpp/src-gen"  module-name="isolated::sc" />
         <factory language="Java" src-dir="isolated-sc-java/src-gen" module-name="isolated.sc" />
      </process>
      <process name="udt1" address="127.0.0.1" port="2417">
         <factory language="C"    src-dir="isolated-udt1-c/src-gen"    module-name="ISOUDT1" />
         <factory language="C++"  src-dir="isolated-udt1-cpp/src-gen"  module-name="isolated::udt1" />
         <factory language="Java" src-dir="isolated-udt1-java/src-gen" module-name="isolated.udt1" />
      </process>
      <process name="ihm1" address="127.0.0.1" port="2418">
         <factory language="C"    src-dir="isolated-ihm1-c/src-gen"    module-name="ISOIHM1" />
         <factory language="C++"  src-dir="isolated-ihm1-cpp/src-gen"  module-name="isolated::ihm1" />
         <factory language="Java" src-dir="isolated-ihm1-java/src-gen" module-name="isolated.ihm1">
            <comp-impl-ref name="distributeur-java" />
         </factory>
         <factory language="Java" src-dir="isolated-ihm1-scripted-java/src-gen" module-name="isolated.scripted.ihm1">
            <comp-impl-ref name="distributeur-scripted" />
         </factory>
      </process>
      <process name="udt2" address="127.0.0.1" port="2419">
         <factory language="C"    src-dir="isolated-udt2-c/src-gen"    module-name="ISOUDT2" />
         <factory language="C++"  src-dir="isolated-udt2-cpp/src-gen"  module-name="isolated::udt2" />
         <factory language="Java" src-dir="isolated-udt2-java/src-gen" module-name="isolated.udt2" />
      </process>
      <process name="ihm2" address="127.0.0.1" port="2420">
         <factory language="C"    src-dir="isolated-ihm2-c/src-gen"    module-name="ISOIHM2" />
         <factory language="C++"  src-dir="isolated-ihm2-cpp/src-gen"  module-name="isolated::ihm2" />
         <factory language="Java" src-dir="isolated-ihm2-java/src-gen" module-name="isolated.ihm2">
            <comp-impl-ref name="distributeur-java" />
         </factory>
      </process>
   </deployment>

   <deployment name="mixed">
      <process-ref deployment="isolated" process="sc" />
      <process name="dab1" address="127.0.0.1" port="2417">
         <factory language="C"    src-dir="mixed-dab1-c/src-gen"    module-name="MIXDAB1" />
         <factory language="C++"  src-dir="mixed-dab1-cpp/src-gen"  module-name="mixed::dab1" />
         <factory language="Java" src-dir="mixed-dab1-java/src-gen" module-name="mixed.dab1">
            <comp-impl-ref name="distributeur-java" />
         </factory>
      </process>
      <process name="dab2" address="127.0.0.1" port="2418">
         <factory language="C"    src-dir="mixed-dab2-c/src-gen"    module-name="MIXDAB2" />
         <factory language="C++"  src-dir="mixed-dab2-cpp/src-gen"  module-name="mixed::dab2" />
         <factory language="Java" src-dir="mixed-dab2-java/src-gen" module-name="mixed.dab2">
            <comp-impl-ref name="distributeur-java" />
         </factory>
      </process>
   </deployment>

   <deployment name="allin">
      <process name="one" address="127.0.0.1" port="2416">
         <factory language="C"    src-dir="allin-one-c/src-gen"    module-name="ALLINONE" />
         <factory language="C++"  src-dir="allin-one-cpp/src-gen"  module-name="allin::one" />
         <factory language="Java" src-dir="allin-one-java/src-gen" module-name="allin.one">
            <comp-impl-ref name="distributeur-java" />
         </factory>
      </process>
   </deployment>

</distributed-application-generation>
